### ISSUE TITLE
Built apps don't work - MacOS, Win10, Linux

### ISSUE THREAD

**Issue by LePhil** [excaliburjs/example-electron#6] opened 2017-12-22 17:27 UTC
Steps to reproduce:
* Clone example-electron repo
* run `npm install`
* change parameter in package.json from `-all` to `-win`
* run `npm run build` from Administrator Command Prompt
* Open app.exe from dist folder

Result: White window with "Electron Boilerplate" as its title.

Expected result: "Hello Electron" on blue background

Same thing happens when building the Mac app on OSX with `--mac` - I can't get the example to run at all - and definitely not my own one. Doesn't seem to be a problem with the code (but can't verify, as I can't access dev console on the built app) - there's no ExcaliburJS loading screen.

**Comment by eonarheim** [comment] 2017-12-22 17:31
@kamranayub Can you take a look?

**Comment by LePhil** [comment] 2017-12-22 17:41
Quick update - same thing happens when building on Ubuntu for Linux (`--linux`)

**Comment by alanag13** [comment] 2017-12-22 19:23
If you add this to the page, you should be able to use F12 to open dev tools:
````javascript
<script>
	document.addEventListener("keydown", function (e) {
		if (e.which === 123) {
			require('remote').getCurrentWindow().toggleDevTools();
}
</script>
````
Does anything show up in the console after that?

**Comment by LePhil** [comment] 2017-12-22 19:42
Nope, can't access devtools, also not with just a keydown listener (and closing `});`).

**Comment by kamranayub** [comment] 2017-12-22 19:55
I just pinned the dependencies, try cloning, deleting `node_modules` and try again; it's working for me with the exact versions. I'm using Node 8 LTS.

I should also update Excalibur to latest. My guess is packager/electron dev stuff updated and broke it. Remember kids, always use exact versions; can't trust semver.

**Comment by alanag13** [comment] 2017-12-22 19:56
lol yes closing parens are important :-)
I pulled this down and was able to reproduce it. Actually you can see in index,js that we're pulling in `electron-debug` which would let you do what I mentioned above without adding anything.

The problem seems to have something to do with the `__dirname` constant being used, If I replace it with my full directory path, it works as expected.

**Comment by kamranayub** [comment] 2017-12-22 19:59
Devtools should be available via View menu too, if it's working.

![image](https://user-images.githubusercontent.com/563819/34311018-5359faee-e720-11e7-9117-b739333a66f6.png)

**Comment by kamranayub** [comment] 2017-12-22 20:01
I just tested fresh node_modules, Node 8.9.3 and npm 5.5.1 on Windows 10. @alanag13 what are your Node versions? Wondering if it's a package or Node issue.

**Comment by kamranayub** [comment] 2017-12-22 20:02
Also, both @alanag13 and @LePhil what's the output of `npm ls --depth 0`?

```
> npm ls --depth 0
app@0.0.0 E:\Development\Contrib\excaliburjs\example-electron
+-- devtron@1.4.0
+-- electron@1.6.8
+-- electron-debug@1.0.0
+-- electron-packager@8.7.0
+-- excalibur@0.10.0
+-- typescript@2.3.2
`-- xo@0.16.0
```

**Comment by alanag13** [comment] 2017-12-22 20:06
Node 8.91
npm 5.5.1

I deleted and re-cloned and im still seeing the issue.

**Comment by LePhil** [comment] 2017-12-22 20:08
```
$ node -v
v9.3.0
$ npm -v
5.5.1
$ npm ls --depth 0
app@0.0.0 /home/phil/git/example-electron-2
├── devtron@1.4.0
├── electron@1.7.10
├── electron-debug@1.4.0
├── electron-packager@8.7.2
├── excalibur@0.10.0
├── typescript@2.6.2
└── xo@0.16.0
```

This is from my Ubuntu machine.

**Comment by kamranayub** [comment] 2017-12-22 20:11
@LePhil Your packages have newer versions than the ones I pinned; can you delete your node_modules and try with the pinned versions?

@alanag13 hmm, interesting! The plot thickens. Can you run the same ls command?

**Comment by kamranayub** [comment] 2017-12-22 20:12
Sorry, it looks like maybe the package-lock was wrong; it should be updated properly now. Try again with a fresh npm install.

**Comment by LePhil** [comment] 2017-12-22 20:14
Yeah that was before I pulled again. Now it's:

```
$ npm ls --depth 0
app@0.0.0 /home/phil/git/example-electron-2
├── devtron@1.4.0
├── electron@1.6.8
├── electron-debug@1.0.0
├── electron-packager@8.7.0
├── excalibur@0.10.0
├── typescript@2.3.2
└── xo@0.16.0
```

**Comment by kamranayub** [comment] 2017-12-22 20:17
That looks good; does it still not work?

**Comment by LePhil** [comment] 2017-12-22 20:20
Unfortunately not, but when I replace `__dirname` with the full path as @alanag13 mentioned, then it works!

**Comment by alanag13** [comment] 2017-12-22 20:21
Mine still doesn't work. Again, if I change `__dirname` in index.js to my full path everything is peachy.
I could update to 8.9.3 but I doubt that's the issue, especially since @LePhil  has a newer version of node and is still seeing the problem. Is it possible I have something installed on my machine that is somehow causing a conflict with `__dirname`? (Or maybe @kamranayub has something that is helpfully making things not conflict`)?

**Comment by kamranayub** [comment] 2017-12-22 20:28
How and where are you running `npm start`?

**Comment by kamranayub** [comment] 2017-12-22 20:31
Oh I get it; this isn't a problem with development (npm start) but build time.

**Comment by LePhil** [comment] 2017-12-22 20:34
Aw poop, doesn't work on the Mac with just replacing `__dirname` :disappointed:

**Comment by LePhil** [comment] 2017-12-22 20:36
I'm running `npm start` from my comfy blue ikea chair in the living room ;)
Also from CLI in the root directory of the repository. But `npm start` has always worked on all 3 platforms, it's just the build that has given me headaches the last couple of hours.

**Comment by kamranayub** [comment] 2017-12-22 20:37
Gotcha; yup I see it too. So weird! Pretty sure I just based this off of electron-boilerplate.

**Comment by LePhil** [comment] 2017-12-22 20:51
Actually it works on the Mac with the manually set __dirname! I think I was in the wrong directory :see_no_evil:

**Comment by kamranayub** [comment] 2017-12-22 20:57
Fixed.

The issue was that when packaged, electron-packager ignores `devDependencies` and excalibur was listed there. I fixed that and also updated to excalibur 0.14

**Comment by alanag13** [comment] 2017-12-22 21:13
ugh, when will I ever learn that whenever I really start digging into the guts of a framework and and not finding any help online that the issue is almost always on my end

**Comment by LePhil** [comment] 2017-12-22 21:31
Aaaah it works! Thanks @kamranayub! You quite literally saved christmas here - just got to finish about 2 dozen open To-Dos until Sunday evening :+1: 

@alanag13 What do you mean?

**Comment by alanag13** [comment] 2017-12-22 21:36
@LePhil I was convinced the problem was with electron or node when really it was an issue with our repo the whole time :-). Thanks again, @kamranayub.

**Closed** 2017-12-22 21:37 UTC

**Comment by kamranayub** [comment] 2017-12-22 21:40
Yeah I am not as familiar with Electron development but I saw the note in
the electron packager README. And I was like... Uh huh, that must be why.
